---
title: 'Week 7: Data Wrangling -- tidyr and dplyr'
---

<div style="margin-bottom:50px;">
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

</div>



# Introduction
In previous labs, we studied how to visualise the spatial objects. In this lab, we will study operations on the data frame (and therefore, sf object). 

Two R packages, *tidyr* and *dplyr*, are designed to simplify the data cleaning and preparation. 

# tidyr

* Please study the *tidyr* package through the following tutorial
https://uc-r.github.io/tidyr. There are five commands
  + %>%: the pipe operator
  + gather
  + spread
  + separate
  + unite

# dplyr

* Please study the *dplyr* package through the following tutorial
https://cran.r-project.org/web/packages/dplyr/vignettes/base.html. The tutorial includes a comparison betwwen commands of *dplyr* and the equivalent from base R. The following commands are especially useful
  + arrange: Arrange rows by variables 
  + filter: Return rows with matching conditions
  + mutate: Create or transform variables
  + select: Select variables by name
  + summarise: Reduce multiple values down to a single value
  
* The above commands only handle a data frame. For the operations in two data frames. Please see *Combine Data Sets* of https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf. (This cheat sheet is also very useful as a future reference). In particular, the following four commands: 
  + left_join
  + right_join
  + inner_join
  + full_join


